### ISSUE TITLE
Do not hang on GCE if Metadata Server is disabled

### ISSUE THREAD

**Issue by lcarva** [vdemeester/k8s-pkg-credentialprovider#18]
This will hang forever if the metadata server is not enabled: https://github.com/vdemeester/k8s-pkg-credentialprovider/blob/802b5fd6c9a9c043749089680a492c8fac9e38a3/gcp/metadata.go#L190-L197

There's an upstream change that plans to make this configurable: https://github.com/kubernetes/kubernetes/commit/a947c32783e9027922762d6f76f5c27926f9bc0a

It looks like that might make its way into the 1.24.X release. Maybe the best way to solve this is just wait for the upstream release and sync here.

**Comment by lcarva** [comment]
Just to clarify the impact, Tekton Chains does not work at all on GCP if the metadata server is disabled.

**Comment by vdemeester** [comment]
Hey @lcarva, thanks for the issue but, I'm going to do the same comment as elsewhere (https://github.com/vdemeester/k8s-pkg-credentialprovider/issues/14#issuecomment-902601489) as this is also written in the [`README.md`](https://github.com/vdemeester/k8s-pkg-credentialprovider#k8siokubernetespkgcredentialprovider-temporary-fork)

> thanks for the report, but this repository is only extracting packages from githb.com/kubernetes/kubernetes (waiting for https://github.com/kubernetes/enhancements/pull/1406 to be merged and most importantly implemented and more widely used). Thus we don't do any changes in there. The issue and proposed change should happen directly in the kubernetes repository, not here.

For the particular issue, I think it might depend on the version of `tektoncd/chains` as since https://github.com/google/go-containerregistry/pull/1234, this repository shouldn't even be a dependency of `tektoncd/chains` anymore (if go-containerregistry has been updated)

Prior to this change, `go-containerregistry` provides a way to disable "at build-time" a specific provider, for example for GCP, there is the following buildtags

```
//go:build !disable_gcp
// +build !disable_gcp
```

This is how OpenShift Pipelines is able to run on GCP, by compiling the project with the `disable_gcp` project.

**Comment by lcarva** [comment]
Great. And it looks like the pkg was updated in chains just a few minutes ago.
